SELECT  CIC_CODIGO AS TCD_CODIGO,
 CIC_CUENTA AS TCD_CTADEB,
 CTA_DESCRI AS TCD_DESCRI,
 CIC_CTAMOD AS TCD_CTAMOD  FROM DPIVATIP_CTA 
 LEFT JOIN dpcta ON CIC_CTAMOD=CTA_CODMOD AND CIC_CUENTA=CTA_CODIGO 
 WHERE CIC_CODINT="CTAVTA" 
 GROUP BY CIC_CODIGO 
 ORDER BY CIC_CODIGO
