SELECT 
DLI_CODSUC AS X_DLI_CODSUC,
DLI_CODIGO AS X_DLI_CODIGO,
INV_DESCRI AS X_INV_DESCRI,
YEAR(DLI_FECHA) AS X_YEAR,
DIA_MES AS X_DIA_MES,
SUM(DLI_CANVTA) AS X_DLI_CANVTA,
COUNT(*) AS X_RECCOUNT 
 FROM DPLIBINVDET 
INNER JOIN DPINV ON INV_CODIGO=DLI_CODIGO 
 INNER JOIN DPDIARIO ON DIA_FECHA=DLI_FECHA 

GROUP BY DLI_CODSUC,DLI_CODIGO,INV_DESCRI,DIA_MES 
ORDER BY DLI_CODSUC,DLI_CODIGO,YEAR(DLI_FECHA)
