SELECT 
 MOV_CODSUC AS INV_CODSUC, INV_CODIGO,
 INV_DESCRI,
 INV_GRUPO ,
 INV_CODMAR,
 MOV_FECHA       AS INV_FECHA ,
 SUM(MOV_CANTID*MOV_CXUND*(MOV_FISICO*-1)) AS INV_CANTID,
 SUM(MOV_PESO  *(MOV_FISICO*-1)) AS INV_PESO  ,
 SUM(MOV_TOTAL *(MOV_FISICO*-1)) AS INV_TOTAL ,
 SUM(MOV_MTODIV*(MOV_FISICO*-1)) AS INV_MTODIV,
 SUM((MOV_MTODIV/MOV_TOTAL)*(MOV_FISICO*-1)) AS INV_VALDIV,
 SUM(MOV_COSTO)            AS INV_COSTO ,
 DATEDIFF(MAX(MOV_FECHA), MIN(MOV_FECHA)) / (COUNT(MOV_FECHA) - 1) AS INV_DIAFRQ, 
 COUNT(*)                  AS INV_COUNT  
 FROM DPMOVINV  INNER JOIN dpinv       ON MOV_CODIGO=INV_CODIGO 
 INNER JOIN dptipdoccli ON MOV_TIPDOC=TDC_TIPO AND TDC_ESTVTA=1 
 WHERE MOV_APLORG="V" AND MOV_INVACT=1 AND MOV_TIPASO<>"NEN" 
 GROUP BY INV_CODSUC,INV_CODIGO,INV_DESCRI,INV_GRUPO,INV_CODMAR,MOV_FECHA 
 ORDER BY MOV_FECHA