SELECT   
 DOC_CODSUC AS CTV_CODSUC,  
 DOC_CODIGO AS CTV_CODIGO,  
 SUM(DOC_BASNET*DOC_CXC) AS  CTV_MONTO   
 FROM DPDOCCLI   
 WHERE LEFT(DATE_SUB(NOW(), INTERVAL &oDp:nDiasCategoria_A DAY) ,10)>=DOC_FECHA AND DOC_TIPTRA="D" AND DOC_ACT=1 AND DOC_CXC<>0   
 GROUP BY DOC_CODSUC,DOC_CODIGO   
 ORDER BY DOC_CODSUC,DOC_CODIGO
