SELECT   
DOC_CODSUC AS DOO_CODSUC,  
DOC_TIPDOC AS DOO_TIPDOC,  
DOC_NUMERO AS DOO_NUMERO  
FROM DPDOCCLI  
INNER JOIN DPTIPDOCCLI ON DOC_TIPDOC=TDC_TIPO AND TDC_LIBVTA=0   
WHERE DOC_CXC<>0 AND DOC_ACT=1 AND DOC_TIPTRA="D"  
  
ORDER BY DOC_CODSUC,DOC_TIPDOC,DOC_NUMERO
