SELECT 
 MOV_CODSUC AS MAR_CODSUC, MAR_CODIGO,
 MAR_DESCRI,
 MOV_FECHA       AS MAR_FECHA ,
 SUM(MOV_CANTID*MOV_CXUND*(MOV_FISICO*-1)) AS MAR_CANTID,
 SUM(MOV_PESO  *(MOV_FISICO*-1)) AS MAR_PESO  ,
 SUM(MOV_TOTAL *(MOV_FISICO*-1)) AS MAR_TOTAL ,
 SUM(MOV_MTODIV*(MOV_FISICO*-1)) AS MAR_MTODIV,
 SUM((MOV_MTODIV/MOV_TOTAL)*(MOV_FISICO*-1)) AS MAR_VALDIV,
 SUM(MOV_COSTO)            AS MAR_COSTO ,
 MIN(MOV_FECHA)            AS MAR_DESDE ,
 MAX(MOV_FECHA)            AS MAR_HASTA ,
 DATEDIFF(MAX(MOV_FECHA), MIN(MOV_FECHA)) / (COUNT(MOV_FECHA) - 1) AS MAR_DIAFRQ, 
 COUNT(*)                  AS MAR_COUNT  
 FROM DPMOVINV  INNER JOIN dpinv       ON MOV_CODIGO=INV_CODIGO 
 INNER JOIN dpmarcas    ON INV_CODMAR=MAR_CODIGO 
 INNER JOIN dptipdoccli ON MOV_TIPDOC=TDC_TIPO AND TDC_ESTVTA=1 
 WHERE MOV_APLORG="V" AND MOV_INVACT=1 AND MOV_TIPASO<>"NEN" 
 GROUP BY MAR_CODSUC,INV_CODMAR,MOV_FECHA 
 ORDER BY MAR_CODSUC,INV_CODMAR,MOV_FECHA