SELECT     
MOV_CODSUC AS VTA_CODSUC,    
MOV_CODCTA AS VTA_CODCTA,    
MOV_CODIGO AS VTA_CODIGO,    
SUM(MOV_CANTID*MOV_CXUND*MOV_CONTAB*-1) AS VTA_CANUND    
FROM DPMOVINV    
WHERE MOV_CONTAB<>0 AND MOV_APLORG="V"    
GROUP BY MOV_CODSUC,MOV_CODCTA,MOV_CODIGO    
ORDER BY MOV_CODSUC,MOV_CODIGO,MOV_CODCTA
