SELECT      
DOC_CODSUC AS VTA_CODSUC,      
DOC_TIPDOC AS VTA_TIPDOC,      
DOC_NUMERO AS VTA_NUMERO,      
DOC_BASNET AS VTA_BASNET,      
DOC_FECHA  AS VTA_FECHA,      
DOC_CODVEN AS VTA_CODVEN,      
DOC_FCHVEN AS VTA_FCHVEN      
   FROM    DPDOCCLI      
INNER JOIN DPTIPDOCCLI ON DOC_TIPDOC=TDC_TIPO AND TDC_COMISI=1      
WHERE DOC_TIPTRA="D" AND DOC_ACT=1
