SELECT 
DLI_CODSUC AS Y_DLI_CODSUC,
DLI_CODIGO AS Y_DLI_CODIGO,
INV_DESCRI AS Y_INV_DESCRI,
YEAR(DLI_FECHA) AS Y_YEAR,
DIA_MES AS Y_DIA_MES,
SUM(DLI_CANVTA) AS Y_DLI_CANVTA,
COUNT(*) AS Y_RECCOUNT 
 FROM DPLIBINVDET 
INNER JOIN DPINV ON INV_CODIGO=DLI_CODIGO 
 INNER JOIN DPDIARIO ON DIA_FECHA=DLI_FECHA 

GROUP BY DLI_CODSUC,DLI_CODIGO,INV_DESCRI,DIA_MES 
ORDER BY DLI_CODSUC,DLI_CODIGO,YEAR(DLI_FECHA)
