SELECT                 
MOC_CODSUC,  
MOC_TIPO,  
MOC_CODAUX,  
MOC_DOCUME,  
MOC_FECHA,  
MOC_NUMCBT,  
MOC_ACTUAL,MOC_TIPTRA,MOC_DOCPAG,                
SUM(IF(MOC_MONTO>0,MOC_MONTO,NULL))    AS MOC_DEBE,                
SUM(IF(MOC_MONTO<0,MOC_MONTO*-1,NULL)) AS MOC_HABER,          
COUNT(*) AS MOC_CANTID,      
MOC_ITEM,  
MOC_CUENTA                
FROM DPASIENTOS                 
WHERE MOC_ORIGEN="VTA"                
GROUP BY MOC_CODSUC,MOC_TIPO,MOC_CODAUX,MOC_DOCUME,MOC_FECHA,MOC_NUMCBT,MOC_DOCPAG,MOC_ACTUAL,MOC_TIPTRA            
ORDER BY MOC_CODSUC,MOC_TIPO,MOC_CODAUX,MOC_DOCUME,MOC_FECHA,MOC_NUMCBT,MOC_DOCPAG,MOC_ACTUAL,MOC_TIPTRA
